// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC_PG6WCHGZpxFlQTRnysaivEI_szYslg',
    appId: '1:944253436216:web:31919054746d814b1b01cd',
    messagingSenderId: '944253436216',
    projectId: 'doctor-app-syria-2026',
    authDomain: 'doctor-app-syria-2026.firebaseapp.com',
    databaseURL: 'https://doctor-app-syria-2026-default-rtdb.firebaseio.com',
    storageBucket: 'doctor-app-syria-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWAFRresrOwA51p-QPBpqF1g2grQ9jHPk',
    appId: '1:944253436216:android:bcb45c567069b75c1b01cd',
    messagingSenderId: '944253436216',
    projectId: 'doctor-app-syria-2026',
    databaseURL: 'https://doctor-app-syria-2026-default-rtdb.firebaseio.com',
    storageBucket: 'doctor-app-syria-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd0BRi-v_cdgQrO34nWy-Itn5q-0dY4kM',
    appId: '1:944253436216:ios:ca4b0bd3b44943711b01cd',
    messagingSenderId: '944253436216',
    projectId: 'doctor-app-syria-2026',
    databaseURL: 'https://doctor-app-syria-2026-default-rtdb.firebaseio.com',
    storageBucket: 'doctor-app-syria-2026.firebasestorage.app',
    iosBundleId: 'com.example.raghadPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd0BRi-v_cdgQrO34nWy-Itn5q-0dY4kM',
    appId: '1:944253436216:ios:ca4b0bd3b44943711b01cd',
    messagingSenderId: '944253436216',
    projectId: 'doctor-app-syria-2026',
    databaseURL: 'https://doctor-app-syria-2026-default-rtdb.firebaseio.com',
    storageBucket: 'doctor-app-syria-2026.firebasestorage.app',
    iosBundleId: 'com.example.raghadPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC_PG6WCHGZpxFlQTRnysaivEI_szYslg',
    appId: '1:944253436216:web:31919054746d814b1b01cd',
    messagingSenderId: '944253436216',
    projectId: 'doctor-app-syria-2026',
    authDomain: 'doctor-app-syria-2026.firebaseapp.com',
    databaseURL: 'https://doctor-app-syria-2026-default-rtdb.firebaseio.com',
    storageBucket: 'doctor-app-syria-2026.firebasestorage.app',
  );
}
